// What each call this app makes costs, read from the pinned spec's own markers.
//
// `spec-weights.json` is generated by `npm run sync-weights` from
// `x-nexus-rate-limit-weight` / `-formula` on the spec tag below, and committed.
// This module is the read side: an operation with a marker costs what the marker
// says, and one without costs 1, which is the spec's rule, not a default picked
// here.

import { readFileSync } from "node:fs";

/** The spec tag the markers were read from. Must equal the SDK's `API_VERSION`. */
export const SPEC_TAG = "v0.8.1";

interface Marker {
  readonly method: string;
  readonly path: string;
  readonly weight: number;
  readonly formula: string | null;
  readonly rateLimitClass: string | null;
}

interface WeightsFile {
  readonly specTag: string;
  readonly sha256: string;
  readonly markers: readonly Marker[];
}

/**
 * The one operation that costs nothing, and it's in prose rather than a marker.
 *
 * "`/account/rate-limit` ... polling it is free: it is the one operation that
 * consumes no tokens." That's why this app can re-read its budgets as often as
 * it likes. It's the only special case, and it's named instead of hidden in
 * the file.
 */
const FREE = new Set(["GET /api/v1/account/rate-limit", "GET /account/rate-limit"]);

function load(): WeightsFile {
  const raw = readFileSync(new URL("./spec-weights.json", import.meta.url), "utf8");
  const parsed = JSON.parse(raw) as WeightsFile;
  if (parsed.specTag !== SPEC_TAG) {
    throw new Error(
      `spec-weights.json was generated from ${parsed.specTag}, but this app is pinned to ${SPEC_TAG}. ` +
        "Run `npm run sync-weights`.",
    );
  }
  return parsed;
}

const FILE = load();
const BY_KEY = new Map(FILE.markers.map((m) => [`${m.method} ${m.path}`, m]));

export const weightsProvenance = `${FILE.specTag} (openapi.json sha256 ${FILE.sha256.slice(0, 12)}…)`;

/**
 * Weight of one call, keyed by method and the spec's path *template*
 * (`/api/v1/orders/{order_id}`, not a concrete id).
 *
 * Batch submission has a formula rather than a flat weight. This app never
 * batches (one child per slice), so a formula here is an error rather than
 * something to evaluate: a limiter that silently charges `1` for a 200-order
 * batch is how you 429 yourself.
 */
export function weightOf(method: string, pathTemplate: string): number {
  const key = `${method.toUpperCase()} ${pathTemplate}`;
  if (FREE.has(key)) return 0;
  const marker = BY_KEY.get(key);
  if (marker === undefined) return 1;
  if (marker.formula !== null) {
    throw new Error(`${key} is weighted by a formula (${marker.formula}); this app does not call it`);
  }
  return marker.weight;
}

/** Every marker, for the test that checks the file is what the app thinks it is. */
export function allMarkers(): readonly Marker[] {
  return FILE.markers;
}
