/*
 * The product, shown rather than described.
 *
 * Everything above this point on the page is an argument. This band is the evidence
 * for it, and it is built out of captures of the running thing: the trading terminal
 * under two brands, the portfolio screen, and a magnified detail of the order ticket.
 *
 * THE RESKIN PAIR IS THE SECOND SIGNATURE. "Brandable UI" is the claim that most
 * needs proving and is cheapest to fake in prose. The two frames are the same screen
 * at the same frozen tick under two palettes, and the reader operates the wipe
 * themselves — see ReskinCompare.tsx for why it is a wipe and not a crossfade.
 *
 * THE CROP IS NOT DECORATION. A full frame shows scale; a crop shows craft. The
 * region chosen is the fee block on the order ticket, because it is the one place in
 * the whole product where a claim this page makes — "your fee is additive, and
 * disclosed to the trader before they submit" — is visible as a row of pixels. The
 * crop is the receipt for the sentence beside it.
 *
 * WHY REAL CAPTURES AND NOT MOCKUPS. Every frame here is the running application at
 * a frozen tick, regenerated by scripts/capture-product-shots.mjs, so a screenshot
 * cannot drift from the product it depicts. The fee row is disclosed to the trader before
 * they submit, and that sentence sits next to the crop that shows it.
 */

import { DIM, FAINT, HI, L1, L2, MUT, PANEL, TXT } from "@/lib/theme";

import { ConsoleTour } from "./ConsoleTour";
import { Crop, Frame, Shot } from "./Frame";
import { MobileShots } from "./MobileShots";
import { ReskinCompare } from "./ReskinCompare";
import { Band, Head, css as s, annotation, body, display, eyebrow } from "./primitives";

const PORTFOLIO = {
  src: "/product/terminal-portfolio.png",
  alt: "The terminal's portfolio screen: total equity with a change figure, an allocation breakdown across spot and perpetuals, open positions with unrealised profit and loss, and a transfer history.",
};

const TICKET = {
  src: "/product/terminal-acme.png",
  alt: "A magnified detail of the Acme Perps order ticket: one maker and taker rate pair reading 0.0150% and 0.0400%, with the venue's own fee already inside those numbers, and the estimated cost of this order beneath them.",
};

export function Product() {
  return (
    <Band id="terminal">
      <Head
        eyebrow="The product"
        title="Your brand on a production trading terminal."
        aside={
          <div style={{ display: "grid", gap: 14 }}>
            {/* The token-module mechanism is stated in ConfigToVenue, where the file that drives
                it is on screen. Here we only need what the reader is looking at. */}
            <p style={{ ...body, fontSize: 14.5 }}>
              {/* The title names the terminal now, so this no longer has to. */}
              Structure is separated from palette, wordmark and typography.
            </p>
            <p style={annotation(FAINT, 11)}>
              Press a venue name. Both frames below are the same build.
            </p>
          </div>
        }
      />

      <div className={s.reveal}>
        <ReskinCompare />
      </div>

      <div className={`${s.split} ${s.splitFlip} ${s.reveal}`} style={{ marginTop: "clamp(28px, 4vw, 44px)" }}>
        <div style={{ display: "grid", gap: 16, minWidth: 0 }}>
          <div>
            <div style={{ ...eyebrow(), marginBottom: 12 }}>The detail that carries the model</div>
            {/* This headline used to read "a separate line on the trader's ticket", which the crop
                beside it, its alt text and the FAQ all contradict: the ticket quotes ONE blended
                maker/taker pair. The separation is in the accounting, not on the trader's screen. */}
            <div style={{ ...display.xs, fontSize: 16, marginBottom: 10 }}>
              Your fee is inside the price your trader sees.
            </div>
            {/* The self-dealing argument lives in the Economics caveat cell, next to the field where
                a reader types their own fee — which is where it is actually needed. */}
            <p style={{ ...body, fontSize: 13.5 }}>
              Additive, not carved out of ours, and named after your venue.
            </p>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "flex-start",
              gap: 10,
              padding: "12px 14px",
              border: `1px solid ${L2}`,
              borderRadius: 6,
            }}
          >
            <span style={annotation(MUT, 11.5)}>
              Disclosed on the ticket, accrued on every fill against your own schedule, and settled at period close.
            </span>
          </div>
        </div>

        <Crop
          spec={TICKET}
          height={228}
          x={1145}
          y={492}
          caption="Order ticket, Acme Perps venue — one maker/taker pair, the venue's own price, with its fee already inside it."
        />
      </div>

      <div className={`${s.split} ${s.reveal}`} style={{ marginTop: "clamp(28px, 4vw, 44px)" }}>
        <Frame label="Terminal · Portfolio" meta="the running app">
          <Shot spec={PORTFOLIO} sizes="(min-width: 1220px) 660px, 96vw" />
        </Frame>

        <div style={{ display: "grid", gap: 16, alignContent: "start", minWidth: 0 }}>
          <div>
            <div style={{ ...eyebrow(), marginBottom: 12 }}>What the trader gets</div>
            {/* The first clause named the four things the capture beside it already shows, and its
                alt text enumerates. The second sentence is the whole point, so it is what survives. */}
            <p style={{ ...body, fontSize: 13.5 }}>
              The screens a team building a venue writes last. They ship with the template.
            </p>
          </div>
          {/* A four-row feature grid stood here. Its rows were the first four cells of the
              Capabilities grid, near-verbatim, three sections apart — and Capabilities is the
              surface whose whole job is lookup and whose count of sixteen is load-bearing. */}
          {/* A note here described our capture apparatus — reduced motion, a frozen tick,
              a command that reproduces the frames. That is how we build the page, not a
              fact a partner needs. */}
        </div>
      </div>

      {/* The phone case, last in the band. A reader who has just seen a dense
          desktop terminal assumes the phone version either does not exist or is the
          desktop squeezed — so it goes after the evidence that earns the doubt. */}
      <div className={s.reveal} style={{ marginTop: "clamp(30px, 4vw, 48px)" }}>
        <div style={{ ...eyebrow(), marginBottom: 12 }}>And on a phone</div>
        <div style={{ ...display.xs, fontSize: 16, marginBottom: 18, maxWidth: "26ch" }}>
          A real phone layout, not a narrower desktop.
        </div>
        <MobileShots />
      </div>
    </Band>
  );
}

/**
 * The console.
 *
 * Its own band rather than a fourth thing inside the one above: the terminal is what
 * the trader sees and the console is what the operator sees, and collapsing the two
 * loses the distinction the offering is built on. It is also the page's densest run
 * of imagery, and a raised band under an inset one is what keeps that from reading as
 * a gallery.
 */
/**
 * The admin API, by what it is for.
 *
 * WHY IT BELONGS HERE. The console tour shows four screens, and a screen tour leaves
 * a reader believing the console IS the operator surface — which would make every
 * operational task a human clicking. The console is one client of an admin API that
 * does everything it does, and that is the difference between a dashboard and a
 * platform: the venue that wants nightly revenue in its own warehouse writes a cron,
 * not a scraper.
 *
 * Grouped as `lib/venue/api-catalog.ts` groups them, because that file is what the
 * console's own API reference renders — if the two disagree, this one is stale.
 */
/* `items` is optional: two of these four groups had an enumeration that the reader had
   already been shown. Analytics listed the four screens of the tour one inch above it, and
   Access was the Capabilities "Team and access" cell verbatim. Both keep their `what` line,
   which is the part doing work. */
const ADMIN_API: { group: string; what: string; items?: string }[] = [
  {
    group: "Analytics",
    what: "Everything the four screens above render, as JSON",
  },
  {
    group: "Reporting",
    what: "The same figures, on a schedule or in a file",
    items: "CSV and JSON export with the provenance labels intact · a scheduled push into your own store",
  },
  {
    group: "Control",
    what: "What an operator does when something is wrong",
    items: "Halt and resume · cancel-all · mint and revoke keys · fund the test account · apply a nexus.json",
  },
  {
    group: "Access",
    what: "Who is allowed to do the above",
  },
];

export function Console() {
  return (
    <Band id="console" tone="raised">
      <Head
        eyebrow="The console"
        title="One console, and every venue's operators sign into it."
        aside={
          <div style={{ display: "grid", gap: 14 }}>
            <p style={{ ...body, fontSize: 14.5 }}>
              Flow, earnings, health and configuration for your venue. We host it, so your audit log and your payout
              details are not sitting in an application you deploy — and a venue stays a static frontend. Four real
              screens, and every figure on them says whether it was measured or estimated.
            </p>
            <p style={annotation(FAINT, 11)}>Pick a screen. The status pill moves with it.</p>
          </div>
        }
      />

      <div className={s.reveal}>
        <ConsoleTour />
      </div>

      {/* The programmatic twin of the four screens above. Deliberately a table of
          groups rather than an endpoint list — an endpoint list on a landing page is
          documentation in the wrong place, and what a reader needs here is whether
          the surface is deep enough to build against. */}
      <div style={{ marginTop: 26 }}>
        <div style={{ display: "flex", alignItems: "baseline", flexWrap: "wrap", gap: "6px 14px", marginBottom: 14 }}>
          <span style={eyebrow(TXT)}>The admin API</span>
          <span style={{ ...annotation(FAINT, 11), margin: 0 }}>
            the console is one client of it — nothing on those screens does something this cannot
          </span>
        </div>
        {/* Four groups, four columns — `.quad`. Auto-fit picks three here and orphans
            Access on a row with two empty cells. */}
        <div className={s.quad} style={{ background: L1, border: `1px solid ${L2}` }}>
          {ADMIN_API.map((g) => (
            <div key={g.group} style={{ background: PANEL, padding: "16px 16px 18px", display: "grid", gap: 7, minWidth: 0 }}>
              <span style={{ ...eyebrow(HI), fontSize: 9.5 }}>{g.group}</span>
              <span style={{ ...body, fontSize: 13 }}>{g.what}</span>
              {g.items ? <span style={{ ...annotation(DIM, 10.5), margin: 0 }}>{g.items}</span> : null}
            </div>
          ))}
        </div>
      </div>

      {/* A "Provenance" note stood here and said two things the reader could already see:
          the live/simulated/estimate labelling is the ConsoleTour caption rendering directly
          above it, and "computed from your own flow" is in Capabilities and the FAQ. A
          paragraph explaining a caption two inches above it is arguing with a demonstration. */}

      <div
        className={s.reveal}
        style={{
          marginTop: 24,
          display: "flex",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "10px 18px",
          paddingTop: 18,
          borderTop: `1px solid ${L1}`,
        }}
      >
        <span style={{ ...eyebrow(DIM) }}>Also real</span>
        {/* The strongest sentence on the page is the one a reader can falsify in one click,
            so it stays a link. What changed is what it is a link TO: the console is our
            application, not a route each venue deploys, so this is an open demo instance of
            the thing rather than a copy shipped inside the template. */}
        <span style={{ ...annotation(FAINT, 11), maxWidth: "72ch" }}>
          The console above is a running application, not a mockup — a demo instance is open at{" "}
          <a href="/admin" className={s.linkQuiet} style={{ color: TXT }}>
            /admin
          </a>
          , loaded with a venue&rsquo;s worth of flow, and it opens without a key. Yours is the same application behind
          your operator login.
        </span>
      </div>
    </Band>
  );
}
